Repository LT-Students/DigitalOffice-CompanyService, pull requests merged in 2020-10, with the labels that each got.

#4 Update xml comments
  src/CompanyService.Broker/CompanyService.Broker.csproj
  src/CompanyService.Business/AddCompanyCommand.cs
  src/CompanyService.Business/AddPositionCommand.cs
  src/CompanyService.Business/CompanyService.Business.csproj
  src/CompanyService.Business/DisablePositionByIdCommand.cs
  src/CompanyService.Business/EditCompanyCommand.cs
  src/CompanyService.Business/EditPositionCommand.cs
  src/CompanyService.Business/GetCompaniesListCommand.cs
  src/CompanyService.Business/GetCompanyByIdCommand.cs
  src/CompanyService.Business/GetPositionByIdCommand.cs
  src/CompanyService.Business/GetPositionsListCommand.cs
  src/CompanyService.Business/Interfaces/IAddCompanyCommand.cs
  src/CompanyService.Business/Interfaces/IAddPositionCommand.cs
  src/CompanyService.Business/Interfaces/IDisablePositionByIdCommand.cs
  src/CompanyService.Business/Interfaces/IEditCompanyCommand.cs
  src/CompanyService.Business/Interfaces/IEditPositionCommand.cs
  src/CompanyService.Business/Interfaces/IGetCompaniesListCommand.cs
  src/CompanyService.Business/Interfaces/IGetCompanyByIdCommand.cs
  src/CompanyService.Business/Interfaces/IGetPositionByIdCommand.cs
  src/CompanyService.Business/Interfaces/IGetPositionsListCommand.cs
  src/CompanyService.Data.Provider.MsSql.Ef/CompanyService.Data.Provider.MsSql.Ef.csproj
  src/CompanyService.Data.Provider/CompanyService.Data.Provider.csproj
  src/CompanyService.Data/CompanyRepository.cs
  src/CompanyService.Data/CompanyService.Data.csproj
  src/CompanyService.Data/Interfaces/ICompanyRepository.cs
  src/CompanyService.Data/Interfaces/IPositionRepository.cs
  src/CompanyService.Data/PositionRepository.cs
  src/CompanyService.Mappers/CompanyService.Mappers.csproj
  src/CompanyService.Models.Db/CompanyService.Models.Db.csproj
  src/CompanyService.Models.Dto/CompanyService.Models.Dto.csproj
  src/CompanyService.Validation/CompanyService.Validation.csproj
  src/CompanyService/CompanyService.csproj
  test/CompanyService.Broker.UnitTests/CompanyService.Broker.UnitTests.csproj
  test/CompanyService.Business.UnitTests/AddCompanyCommandTests.cs
  test/CompanyService.Business.UnitTests/AddPositionCommandTests.cs
  test/CompanyService.Business.UnitTests/CompanyService.Business.UnitTests.csproj
  test/CompanyService.Business.UnitTests/EditCompanyCommandTests.cs
  test/CompanyService.Business.UnitTests/EditPositionCommandTests.cs
  test/CompanyService.Data.UnitTests/CompanyRepositoryTests.cs
  test/CompanyService.Data.UnitTests/CompanyService.Data.UnitTests.csproj
  test/CompanyService.Data.UnitTests/PositionRepositoryTests.cs
  test/CompanyService.Mappers.UnitTests/CompanyService.Mappers.UnitTests.csproj
Labels: documentation

#5 Fix cors url
  src/CompanyService/appsettings.json
Labels: bug

#6 AddDepartment endpoint
  src/CompanyService.Business/AddDepartmentCommand.cs
  src/CompanyService.Business/Interfaces/IAddDepartmentCommand.cs
  src/CompanyService.Data/DepartmentRepository.cs
  src/CompanyService.Data/Interfaces/IDepartmentRepository.cs
  src/CompanyService.Mappers/CompanyService.Mappers.csproj
  src/CompanyService.Mappers/DepartmentMapper.cs
  src/CompanyService.Models.Dto/DepartmentRequest.cs
  src/CompanyService.Validation/DepartmentRequestValidator.cs
  src/CompanyService/CompanyService.csproj
  src/CompanyService/Controllers/DepartmentController.cs
  src/CompanyService/Startup.cs
  test/CompanyService.Business.UnitTests/AddDepartmentCommandTests.cs
  test/CompanyService.Data.UnitTests/DepartmentRepositoryTests.cs
  test/CompanyService.Mappers.UnitTests/DepartmentMapperTests.cs
  test/CompanyService.Validation.UnitTests/DepartmentRequestValidatorTests.cs
Labels: enhancement

#7 Added Models.Broker layer
  LT.DigitalOffice.CompanyService.sln
  src/CompanyService.Broker/CompanyService.Broker.csproj
  src/CompanyService.Models.Broker/CompanyService.Models.Broker.csproj
  src/CompanyService.Models.Broker/Requests/IGetUserPositionRequest.cs
  src/CompanyService.Models.Broker/Responses/IUserPositionResponse.cs
Labels: enhancement
