Repository LT-Students/DigitalOffice-CompanyService, pull requests merged in 2021-05, with the labels that each got.

#22 update GetDepartmentConsumer
  src/CompanyService.Broker/Consumers/GetDepartmentConsumer.cs
  src/CompanyService.Models.Broker/Responses/IGetDepartmentResponse.cs
Labels: enhancement

#24 Fix response mapper (add id)
  src/CompanyService.Mappers/Responses/PositionResponseMapper.cs
  test/CompanyService.Mappers.UnitTests/Responses/PositionResponseMapperTests.cs
Labels: bug

#25 Update version
  src/CompanyService/Startup.cs
Labels: documentation
