Repository LT-Students/DigitalOffice-CompanyService, pull requests merged in 2021-07, with the labels that each got.

#31 fix list of skip endpoints and rework getCompanyCommand
  src/CompanyService.Data/CompanyRepository.cs
  src/CompanyService.Mappers/Models/CompanyInfoMapper.cs
  src/CompanyService/appsettings.json
  test/CompanyService.Data.UnitTests/CompanyRepositoryTests.cs
  test/CompanyService.Mappers.UnitTests/Models/CompanyInfoMapperTests.cs
Labels: bug, enhancement

#32 changed class to record
  src/CompanyService.Models.Dto/Models/AdminInfo.cs
  src/CompanyService.Models.Dto/Models/BaseDepartmentInfo.cs
  src/CompanyService.Models.Dto/Models/CompanyInfo.cs
  src/CompanyService.Models.Dto/Models/DepartmentInfo.cs
  src/CompanyService.Models.Dto/Models/DepartmentUserInfo.cs
  src/CompanyService.Models.Dto/Models/ImageInfo.cs
  src/CompanyService.Models.Dto/Models/OfficeInfo.cs
  src/CompanyService.Models.Dto/Models/PositionInfo.cs
  src/CompanyService.Models.Dto/Models/SMTPInfo.cs
  src/CompanyService.Models.Dto/Models/ShortDepartmentInfo.cs
  src/CompanyService.Models.Dto/Models/UserInfo.cs
  src/CompanyService.Models.Dto/Requests/AddImageRequest.cs
  src/CompanyService.Models.Dto/Requests/CreateCompanyRequest.cs
  src/CompanyService.Models.Dto/Requests/CreateDepartmentRequest.cs
  src/CompanyService.Models.Dto/Requests/CreateOfficeRequest.cs
  src/CompanyService.Models.Dto/Requests/CreatePositionRequest.cs
  src/CompanyService.Models.Dto/Responses/DepartmentsResponse.cs
  src/CompanyService.Models.Dto/Responses/FindOfficesResponse.cs
  src/CompanyService.Models.Dto/Responses/PositionResponse.cs
Labels: enhancement

#33 Fixed validations
  src/CompanyService.Validation/BaseDepartmentInfoValidator.cs
  src/CompanyService.Validation/CreatePositionRequestValidator.cs
  test/CompanyService.Validation.UnitTests/BaseDepartmentInfoValidatorTests.cs
  test/CompanyService.Validation.UnitTests/CreatePositionRequestValidatorTests.cs
Labels: bug

#34 fixed create department and find department endpoints
  src/CompanyService.Business/Commands/Department/CreateDepartmentCommand.cs
  src/CompanyService.Business/Commands/Department/FindDepartmentsCommand.cs
  src/CompanyService.Business/Commands/Department/Interfaces/ICreateDepartmentCommand.cs
  src/CompanyService.Business/Commands/Position/CreatePositionCommand.cs
  src/CompanyService.Business/Commands/Position/Interfaces/ICreatePositionCommand.cs
  src/CompanyService.Models.Dto/Configuration/RabbitMqConfig.cs
  src/CompanyService.Models.Dto/Responses/DepartmentsResponse.cs
  src/CompanyService/Controllers/DepartmentController.cs
  src/CompanyService/Controllers/PositionController.cs
  src/CompanyService/Startup.cs
  test/CompanyService.Business.UnitTests/Commands/Department/CreateDepartmentCommandTests.cs
  test/CompanyService.Business.UnitTests/Commands/Department/FindDepartmentsCommandTests.cs
  test/CompanyService.Business.UnitTests/Commands/Position/CreatePositionCommandTests.cs
Labels: bug

#36 add get users departments and positions consumer
  Common.Configurations.targets
  src/CompanyService.Broker/Consumers/GetUsersDepartmentsUsersPositionsConsumer.cs
  src/CompanyService.Business/Commands/Department/FindDepartmentsCommand.cs
  src/CompanyService.Data/DepartmentUserRepository.cs
  src/CompanyService.Data/Interfaces/IDepartmentUserRepository.cs
  src/CompanyService.Data/Interfaces/IPositionUserRepository.cs
  src/CompanyService.Data/PositionUserRepository.cs
  src/CompanyService.Models.Dto/Configuration/RabbitMqConfig.cs
  src/CompanyService/Startup.cs
  src/CompanyService/appsettings.json
Labels: enhancement

#38 added director userInfo to response and check of userData
  src/CompanyService.Business/Commands/Department/FindDepartmentsCommand.cs
Labels: bug

#39 Fix GetPositionConsumer
  src/CompanyService.Broker/Consumers/GetPositionConsumer.cs
  test/CompanyService.Broker.UnitTests/GetUserPositionConsumerTests.cs
Labels: bug

#41 fix github actions
  .github/workflows/main.yml
Labels: documentation

#43 update validator
  src/CompanyService.Mappers/Db/DbOfficeMapper.cs
  src/CompanyService.Mappers/Db/DbPositionMapper.cs
  src/CompanyService.Mappers/Models/BaseDepartmentInfoMapper.cs
  src/CompanyService.Validation/Department/BaseDepartmentInfoValidator.cs
  src/CompanyService.Validation/Department/EditDepartmentRequestValidator.cs
  src/CompanyService.Validation/Office/CreateOfficeRequestValidator.cs
  src/CompanyService.Validation/Position/CreatePositionRequestValidator.cs
  src/CompanyService.Validation/Position/EditPositionRequestValidator.cs
  test/CompanyService.Validation.UnitTests/CreateOfficeRequestValidatorTests.cs
Labels: bug

#45 fix repositories
  src/CompanyService.Data/DepartmentUserRepository.cs
  src/CompanyService.Data/PositionUserRepository.cs
Labels: bug

#44 fix mappers
  src/CompanyService.Mappers/Db/DbOfficeMapper.cs
  src/CompanyService.Mappers/Db/DbPositionMapper.cs
  src/CompanyService.Mappers/Models/BaseDepartmentInfoMapper.cs
Labels: bug

#46 Reworked get department
  src/CompanyService.Business/Commands/Department/GetDepartmentCommand.cs
  src/CompanyService.Mappers/Models/CompanyInfoMapper.cs
  src/CompanyService.Mappers/Models/Interfaces/IShortDepartmentInfoMapper.cs
  src/CompanyService.Mappers/Models/ShortDepartmentInfoMapper.cs
  src/CompanyService.Mappers/Responses/DepartmentResponseMapper.cs
  src/CompanyService.Models.Dto/Models/ShortDepartmentInfo.cs
  test/CompanyService.Mappers.UnitTests/Models/CompanyInfoMapperTests.cs
  test/CompanyService.Mappers.UnitTests/Models/ShortDepartmentsInfoMapperTests.cs
Labels: bug

#47 fix takeCount
  src/CompanyService.Data/DepartmentUserRepository.cs
  src/CompanyService.Data/OfficeRepository.cs
  test/CompanyService.Data.UnitTests/DepartmentUserRepositoryTests.cs
  test/CompanyService.Data.UnitTests/OfficeRepositoryTests.cs
Labels: bug

#48 fixed get and find user position
  Common.Configurations.targets
  src/CompanyService.Broker/Consumers/ChangeUserPositionConsumer.cs
  src/CompanyService.Business/Commands/Position/EditPositionCommand.cs
  src/CompanyService.Business/Commands/Position/FindPositionsCommand.cs
  src/CompanyService.Business/Commands/Position/Interfaces/IFindPositionsCommand.cs
  src/CompanyService.Data/Interfaces/IPositionRepository.cs
  src/CompanyService.Data/Interfaces/IPositionUserRepository.cs
  src/CompanyService.Data/PositionRepository.cs
  src/CompanyService.Data/PositionUserRepository.cs
  src/CompanyService/Controllers/DepartmentController.cs
  src/CompanyService/Controllers/PositionController.cs
  test/CompanyService.Business.UnitTests/Commands/Position/GetPositionsListCommandTests.cs
  test/CompanyService.Data.UnitTests/PositionRepositoryTests.cs
  test/CompanyService.Data.UnitTests/PositionUserRepositoryTests.cs
Labels: bug

#50 Fix get department
  src/CompanyService.Business/Commands/Department/GetDepartmentCommand.cs
  src/CompanyService.Mappers/Models/DepartmentUserInfoMapper.cs
  src/CompanyService.Mappers/Responses/DepartmentResponseMapper.cs
Labels: bug

#49 Docs/change actions
  .github/workflows/main.yml
Labels: documentation

#51 add uniqueConstraint to position name
  src/CompanyService.Business/Commands/Department/CreateDepartmentCommand.cs
  src/CompanyService.Business/Commands/Department/EditDepartmentCommand.cs
  src/CompanyService.Business/Commands/Position/CreatePositionCommand.cs
  src/CompanyService.Business/Commands/Position/EditPositionCommand.cs
  src/CompanyService.Data.Provider.MsSql.Ef/Migrations/20210715235900_AddUniqueConstraintToPositionAndToDepartmentName.cs
  src/CompanyService.Data/DepartmentRepository.cs
  src/CompanyService.Data/Interfaces/IDepartmentRepository.cs
  src/CompanyService.Data/Interfaces/IPositionRepository.cs
  src/CompanyService.Data/PositionRepository.cs
  src/CompanyService/Controllers/DepartmentController.cs
  src/CompanyService/Controllers/PositionController.cs
  test/CompanyService.Business.UnitTests/Commands/Department/CreateDepartmentCommandTests.cs
Labels: bug

#52 fix 409 status response
  src/CompanyService/Controllers/DepartmentController.cs
Labels: bug

#57 fix
  src/CompanyService.Broker/Consumers/GetDepartmentConsumer.cs
Labels: bug

#58 fix create departments and company
  src/CompanyService.Business/Commands/Company/CreateCompanyCommand.cs
  src/CompanyService.Business/Commands/Department/CreateDepartmentCommand.cs
Labels: bug

#56 fix position response
  src/CompanyService.Business/Commands/Position/GetPositionCommand.cs
  src/CompanyService.Business/Commands/Position/Interfaces/IGetPositionCommand.cs
  src/CompanyService.Data/DepartmentRepository.cs
  src/CompanyService.Data/PositionRepository.cs
  src/CompanyService.Mappers/Responses/Interfaces/IPositionResponseMapper.cs
  src/CompanyService.Mappers/Responses/PositionResponseMapper.cs
  src/CompanyService.Models.Dto/Responses/PositionResponse.cs
  src/CompanyService/Controllers/PositionController.cs
  src/CompanyService/Startup.cs
  test/CompanyService.Business.UnitTests/Commands/Position/GetPositionCommandTests.cs
  test/CompanyService.Business.UnitTests/Commands/Position/GetPositionsListCommandTests.cs
Labels: bug

#59 update version of models
  Common.Configurations.targets
  src/CompanyService.Mappers/Models/DepartmentUserInfoMapper.cs
Labels: enhancement
